export interface Cliente {
  code: string;
  name: string;
}

export const CLIENTES: Cliente[] = [
  { code: "3", name: "CUXACH S.A." },
  { code: "4", name: "JASA MATERIAL DE CONSTRUCCION S.A." },
  { code: "6", name: "AGRUPACIO CONSTRUCTORA DE LLEVANT S.A." },
  { code: "7", name: "GALMES MAC S.L." },
  { code: "8", name: "HERMANOS PALLICER PONS S.A." },
  { code: "13", name: "LORENZO RAMIS LLABRES" },
  { code: "14", name: "MAINCA S.A." },
  { code: "15", name: "MATERIAL DE CONSTRUCCION GALMES S.A." },
  { code: "16", name: "VERGER MATERIALS ES PLA S.L." },
  { code: "18", name: "MIGUEL SOCIAS E HIJOS, S.L." },
  { code: "19", name: "TEULERA CAN BENITO S.L." },
  { code: "20", name: "PREFABRICATS RIUTORT S.L." },
  { code: "21", name: "JUAN FERRIOL E HIJOS S.L." },
  { code: "22", name: "TREBALL DEL BOSC S.L." },
  { code: "23", name: "SANTANDREU SUREDA S.L." },
  { code: "25", name: "SON FORNES S.A." },
  { code: "26", name: "VICENTE PONS AMER" },
  { code: "29", name: "T T SERRA S.L." },
  { code: "31", name: "EUROGRES BALEAR S.L." },
  { code: "32", name: "PUJOL SASTRE S.L." },
  { code: "33", name: "MURO SUMINIS. DE ALBAÑILE. S.L." },
  { code: "34", name: "CONSTRUCCION MODERNA S.L." },
  { code: "35", name: "ALMACENES FEMENIAS S.A." },
  { code: "36", name: "MAGATZEM DES PLA S.L." },
  { code: "38", name: "JERONIMO LLOBERA MARCH" },
  { code: "39", name: "AMENGUAL DOLS S.A." },
  { code: "40", name: "LEROY MERLIN S.L.U." },
  { code: "42", name: "BAIX DE LA VILA S.L." },
  { code: "43", name: "JAIME NAVARRO S.L." },
  { code: "44", name: "MATERIALS DE CONSTRUCCIO MAIRATA S.L." },
  { code: "45", name: "MATERIAL DE CONSTRUCCIO TONI LLULL S.L." },
  { code: "46", name: "PREFAL S.L." },
  { code: "47", name: "MAGATZEMS DE MARRATXI S.L." },
  { code: "48", name: "MATERIAL DE CONSTRUCCIO DES RAIGUER S.L." },
  { code: "49", name: "TODO PARA LA CASA S.L." },
  { code: "52", name: "CONSTRUCCIONS SORT D'ENFORA S.L." },
  { code: "53", name: "GOMEZ QUINTERO S.A." },
  { code: "54", name: "TOLO FLORIT S.A." },
  { code: "56", name: "UTE DESDOBLAMENT C715" },
  { code: "57", name: "HERTORRES S.L." },
  { code: "59", name: "EMPRESA DE TRANSFORMACION AGRARIA S.A." },
  { code: "61", name: "SIQUIER S.A." },
  { code: "62", name: "FRONTERA RIERA S.L." },
  { code: "64", name: "OBRAS Y PROMOCIONES COMAS S.A." },
  { code: "65", name: "FRANCISCO NICOLAU FEMENIAS" },
  { code: "67", name: "OBRES COMES BELTRAN S.L." },
  { code: "68", name: "CONSTRUCCIONS MARTET S.L." },
  { code: "69", name: "ARQUITECTURA POPULAR DE MALLORCA S.L." },
  { code: "73", name: "CONSTRUCCIONS ARTIGUES TRUYOLS S.L." },
  { code: "74", name: "MAGRIPALMA S.L." },
  { code: "75", name: "PASTOR S.A." },
  { code: "76", name: "MANERA C.B." },
  { code: "77", name: "J.B. C.B." },
  { code: "78", name: "PRETENSATS SA COVA S.A." },
  { code: "79", name: "TAUPER S.L." },
  { code: "80", name: "VIBRADOS BARCELO S.L." },
  { code: "81", name: "UNICMALL S.L." },
  { code: "82", name: "VIBRADOS Y PRETEN. MANACOR S.A." },
  { code: "84", name: "VIBRATS MARIA DE LA SALUD S.L." },
  { code: "85", name: "FRANCISCO GRIMALT S.A." },
  { code: "86", name: "CANTERA SON TEY S.L." },
  { code: "87", name: "SANCHO VAQUER C.B." },
  { code: "88", name: "PALERM S.A." },
  { code: "89", name: "CALIZAS MANACOR 1995 S.L." },
  { code: "90", name: "JUPE, MATERIALS DE CONSTRUCCIÓ S.L." },
  { code: "91", name: "BALUSTRADAS LLEVANT S.L." },
  { code: "92", name: "CALIZAS BIBILONI S.A." },
  { code: "93", name: "MARMOLERIA MASSANET C.B." },
  { code: "94", name: "TROSSOS DE MARES S.L." },
  { code: "95", name: "T.I.E. ES PLA DE SES ROTES S.L." },
  { code: "96", name: "A. I S. GRAVERA CAN ALOU, S.L." },
  { code: "97", name: "POZOS MALLORCA S.L." },
  { code: "98", name: "JUAN SASTRE ROCA S.L." },
  { code: "99", name: "LLABRES FELIU OBRA CIVIL" },
  { code: "100", name: "ANDRES NAVARRO COLL" },
  { code: "101", name: "ANTONIO FONT MATAS" },
  { code: "102", name: "BERNARDINO CLADERA CAIMARI" },
  { code: "103", name: "TRANSMURO MALLORCA S.L." },
  { code: "105", name: "FRANCISCO JAVIER PARDO RAMON" },
  { code: "107", name: "INSTITUT BALEAR DE LA NATURA" },
  { code: "108", name: "RECONSMUR S.L." },
  { code: "109", name: "CONSTRUC. BARTOMEU ADROVER S.L." },
  { code: "110", name: "AMER E HIJOS S.A." },
  { code: "112", name: "JUANA SUREDA LASCOLAS" },
  { code: "113", name: "JAIME JUAN S.L." },
  { code: "114", name: "TOMEU BO S.L." },
  { code: "115", name: "EDYMA SILLOT S.L." },
  { code: "117", name: "MIQUEL COLL FIOL" },
  { code: "118", name: "JOSE TORRES TORRES" },
  { code: "119", name: "GABRIEL SERRA CANTALLOPS" },
  { code: "120", name: "JOAQUIN ESTESO S.L." },
  { code: "121", name: "MARGERS I MANOBRES S.L." },
  { code: "122", name: "JOSE MARIA ROTGER MARTINEZ" },
  { code: "124", name: "MARMOLES GAMUNDI S.L." },
  { code: "125", name: "AGUAS DE LLUCH S.A." },
  { code: "126", name: "C. A. SEGUI SOCIAS I DESC. S.R.L." },
  { code: "129", name: "CONTENIDORS MURO S.L." },
  { code: "131", name: "FERROVIAL AGROMAN S.A." },
  { code: "132", name: "OBRAS Y PAVIMENTACIONES MAN S.A.U." },
  { code: "133", name: "COEXA S.A." },
  { code: "134", name: "MELCHOR MASCARO S.A." },
  { code: "137", name: "SANTUARI DE LLUCH" },
  { code: "138", name: "TRANSPORTES J. SANCHEZ S.A." },
  { code: "140", name: "MONNABER NOU S.A." },
  { code: "141", name: "DESMONTES Y EXCAVACIONES POLLENÇA SL" },
  { code: "142", name: "PRODUCTORA MANACOR S.A.U." },
  { code: "143", name: "MASGUAIT S.L." },
  { code: "144", name: "MARTI CERDO S.L." },
  { code: "145", name: "FRONTERA E HIJOS S.L." },
  { code: "146", name: "AJUNTAMENT DE SANTA MARGALIDA" },
  { code: "149", name: "NOEL CHAPIRA ROSSELLO" },
  { code: "150", name: "TOMEU MIRALLES ADROVER" },
  { code: "151", name: "MATERIAL CONST. CAN GAYA S.L." },
  { code: "152", name: "EXCAVACIONES OLIVER S.A." },
  { code: "153", name: "TECNO SONDEO BALEAR S.L." },
  { code: "154", name: "PAVIMENTOS QUIMIPRES BALEAR S.L." },
  { code: "158", name: "J. LLITERAS MULET S.L." },
  { code: "159", name: "EDIFICACIONES OBRADOR ROSSELLO S.L." },
  { code: "160", name: "MASSANELLA GRES S.A.U." },
  { code: "161", name: "CAN RIERA S.L." },
  { code: "162", name: "VICENS SERRA" },
  { code: "164", name: "TRANSNORD S.L." },
  { code: "165", name: "INCOMARSA" },
  { code: "167", name: "MATERIAL CONST. SIMONET S.L." },
  { code: "169", name: "OBRES I SERVEIS ULLARO S.L." },
  { code: "170", name: "CONST LLULL SASTRE S.A." },
  { code: "172", name: "CANTERA SES FONTANELLES S.L." },
  { code: "175", name: "VADELL CRESPI S.L." },
  { code: "176", name: "MARIA CAÑELLAS CAÑELLAS" },
  { code: "177", name: "TRANS. Y SERV. FERRER CASTELL S.L." },
  { code: "178", name: "CANTERA CAN TOMEU S.L." },
  { code: "179", name: "KELLERTERRA S.L." },
  { code: "181", name: "AJUNTAMENT DE PETRA" },
  { code: "182", name: "NICOLAS MARTORELL S.L." },
  { code: "183", name: "PERFORACIONES ROIG S.L." },
  { code: "184", name: "MARIA RIUTORT RIERA" },
  { code: "185", name: "A M C CAN TONIO S.L." },
  { code: "186", name: "M C COLONIA SAN PEDRO S.L." },
  { code: "188", name: "FILLS DE FRANCISCA VAQUER S.L." },
  { code: "189", name: "CONSTRUCCIONS BIEL GALMES S.L." },
  { code: "192", name: "RESTAURANT SES TORRES" },
  { code: "193", name: "TRANSPORTE SASTRE RAMIS S.L." },
  { code: "194", name: "SACARES QUETGLAS CONST. S.L." },
  { code: "196", name: "CONST. SEBASTIA GOMIS SL" },
  { code: "197", name: "CODI PERSONAL DE CANTERA*************" },
  { code: "199", name: "TRANSPORTS J. GARI S.L." },
  { code: "200", name: "CURIENT S.A." },
  { code: "201", name: "GRES MALLORCA S.L." },
  { code: "202", name: "FONT E HIJOS S.A." },
  { code: "205", name: "GRAVERA CAN HERRAEZ S.L." },
  { code: "206", name: "CRISTOBAL TORRES PONS" },
  { code: "207", name: "FONTUBE MALLORCA, S.L." },
  { code: "211", name: "MAT. DE CONSTRUCCIO CALA D'OR S.L." },
  { code: "212", name: "MORANTA S.L." },
  { code: "215", name: "CA'S SAGRISTA S.L." },
  { code: "217", name: "TONI RIUTORT SANSO" },
  { code: "218", name: "SUMINISTRES SON AMONDA S.L." },
  { code: "220", name: "MAGATZEM SES PREDERES S.L." },
  { code: "221", name: "PROMOCIONES SEDRA S.L." },
  { code: "222", name: "MATERIAL DE CONSTRUCCIO BALAGUER, S.L." },
  { code: "224", name: "CONSTRUCCIONS VALLS AMENGUAL S.L." },
  { code: "225", name: "RAFEL TRUCO S.L." },
  { code: "227", name: "CONST. I PAV. BME RAMON S.A." },
  { code: "228", name: "GRUAS Y CONTENEDORES A CASTRO, S.L." },
  { code: "230", name: "JUAN TERRASA JULIA" },
  { code: "231", name: "CONST. JOAN ADROVER S.L." },
  { code: "233", name: "TRANSFORTEZA S.L." },
  { code: "234", name: "SON SERRA 2003 S.L." },
  { code: "238", name: "CONTENIDORS FULLANA S.L." },
  { code: "241", name: "TRANSPORTS GERMANS SANSO ROSSELLO,S.L." },
  { code: "245", name: "MIRAVER DISSENY CONSTRUCCIO S.L." },
  { code: "247", name: "PRESCON OBRA PUBLICA S.A." },
  { code: "249", name: "ES PUNTIRO S.L." },
  { code: "252", name: "SES COLUMNES S.L." },
  { code: "253", name: "PREBESEC MALLORCA S.A." },
  { code: "254", name: "PROMOCIONS ROTLLE DE SITJA S.L." },
  { code: "257", name: "CONTRUC. OBRES PUBLIQUES CRESPI S.L." },
  { code: "259", name: "TOFOL CANAVES GARAU" },
  { code: "260", name: "PERLIPLAC S.L." },
  { code: "261", name: "SA CIMENTERA S.A" },
  { code: "262", name: "M C MARTORELL TORRANDELL S.L." },
  { code: "263", name: "ANTONIO MARTORELL ADROVER" },
  { code: "264", name: "MALLORQU. DE OBRAS Y CONTR. S.L." },
  { code: "265", name: "PEDRERES CA'N RAMIS S.L." },
  { code: "266", name: "TRANSPORTS MARANEU S.L." },
  { code: "268", name: "MARES PREFABRICATS S.L." },
  { code: "270", name: "MAT. CAN VIDAL DE SANTANYI S.L." },
  { code: "272", name: "MON-BLANC C.B." },
  { code: "277", name: "CONTRUCCINES LLABINE S.A." },
  { code: "278", name: "TUBOS Y BLOQUES FIOL S.A." },
  { code: "284", name: "CONSTRUCCIONS FONS-ESTEL, S.L." },
  { code: "285", name: "AGLOMERADOS DE FELANITX S.A." },
  { code: "287", name: "COEXPOL S.L." },
  { code: "288", name: "NORT DE ALCUDIA S.L." },
  { code: "289", name: "CONSTRUCCIONS MULET CAMPINS S.L." },
  { code: "291", name: "MARTINEZ Y GARAU S.L." },
  { code: "293", name: "CONST. QUINTERO,S.L." },
  { code: "294", name: "TRANSPORT. MUÑOZ-FERRERA S.L." },
  { code: "295", name: "T.M.C. MORLA MASCARO S.L." },
  { code: "296", name: "T.M.C. PEDRO SALAS CALDENTEY" },
  { code: "298", name: "PIVITA S.A.U." },
  { code: "301", name: "AGUAMAR TENIS Y PISCINAS S.L." },
  { code: "305", name: "EXCAVACIONES SAN FERRIOL S.L." },
  { code: "306", name: "MAT. PARA LA CONST. PALERM S.A." },
  { code: "310", name: "AGRICOLA LIMITADA SIMO TORT SC" },
  { code: "311", name: "TOMAS SIQUIER I FILLS S.L." },
  { code: "312", name: "CIMENTS DE BALEARS S.A." },
  { code: "313", name: "AÑEDUL S.L." },
  { code: "315", name: "LLORENS PERELLO VIDAL" },
  { code: "317", name: "DIALMA S.A." },
  { code: "319", name: "SES BASSES S.L TEULERA I PREF." },
  { code: "321", name: "CONTRATAS BARTOLOME RAMON S.A." },
  { code: "322", name: "PAVIMENT BARTOLOME RAMON S.A." },
  { code: "324", name: "MATER I PROMOCIONS MALLORCA S.L." },
  { code: "325", name: "JAIME GRIMALT MASSOT S.L." },
  { code: "328", name: "INDUSTRIAL VOLTOR 44(IB) S.L." },
  { code: "330", name: "TTES, GRUES I EXCAVACIONS CAIMARI S.L." },
  { code: "331", name: "MACTEYDO S.L." },
  { code: "336", name: "FERRET. Y CONST. C. RIGO S.L." },
  { code: "337", name: "AGLOMERADOS MALLORCA S.A." },
  { code: "338", name: "VIA Y OBRAS PUBLICAS S.A." },
  { code: "339", name: "MAGATZEM CAN MOLL S.L." },
  { code: "343", name: "CONSTRUCCIONS CREATIVES J DANUS S.L." },
  { code: "345", name: "ISCOMAR SA" },
  { code: "347", name: "VIBRATS BALLESTER S.A." },
  { code: "351", name: "CONST. JOAN ALOMAR SL" },
  { code: "352", name: "BALEAR 2002 CONTRAT Y SERV. S.L." },
  { code: "354", name: "SEBASTIA LLINAS NICOLAU" },
  { code: "356", name: "EXPLOT. TURISTIQUES DE LES ILLES S.L." },
  { code: "357", name: "MIQUEL RIUTORT BUSQUETS" },
  { code: "359", name: "TRANSPORTES PEDRO BOYERAS S.L." },
  { code: "361", name: "MAGATZEM SES FORQUES S.L." },
  { code: "362", name: "VIDAL FULLANA S.L." },
  { code: "363", name: "FULLANA E HIJOS S.A." },
  { code: "364", name: "OBRES DE LES ILLES S.L." },
  { code: "365", name: "EXCAVACIONES HNOS. RIERA CANALS SL" },
  { code: "367", name: "SALVADOR PASTOR S.L." },
  { code: "370", name: "PISCINAS TENIS 95 S.L." },
  { code: "371", name: "CONSTRUCCIONS MIJOAN, S.L." },
  { code: "372", name: "BALUSTRADAS PALMA S.L." },
  { code: "373", name: "CONSTRUCCIONS JOAN CAPO S.L." },
  { code: "375", name: "BARTOLOME LLOMPART CORRO" },
  { code: "377", name: "JAUME FERRAGUT FERRA" },
  { code: "378", name: "MIQUEL MORA BARCELO" },
  { code: "379", name: "MIQUEL REBASSA LLULL" },
  { code: "382", name: "CERAMIA ESPACIOS S.L." },
  { code: "383", name: "JOAN ALZAMORA ROSSELLO" },
  { code: "385", name: "FERRETERIA BONANY,S.L." },
  { code: "388", name: "KRONSA INTERNACIONAL,S.A." },
  { code: "390", name: "SA MARINA DE SON GUAL S.L." },
  { code: "391", name: "TRAEXFRANC S.L.U." },
  { code: "394", name: "MIJUPE ARTA S.L." },
  { code: "395", name: "SANTIAGO AT S.L." },
  { code: "398", name: "TRANS. I S. LLITERES I FILLS S.L." },
  { code: "400", name: "OBRES I SERVEIS ES PLA C.B." },
  { code: "401", name: "BALAUSTRES I DERIV. DE BALEARS S.L." },
  { code: "410", name: "IGNACIO MORRO S.L.U." },
  { code: "414", name: "CAS SOCIS, S.L." },
  { code: "417", name: "MAGATZEM ANDRATX S.L." },
  { code: "418", name: "CONTROL BLAU-Q S.L." },
  { code: "421", name: "PAVIMENTOS MALLORCA S.L." },
  { code: "422", name: "EQUIPS SEG I PROTECC. INDIVIDUAL S.L." },
  { code: "423", name: "CONSTRUCCIONS REMOL C.B." },
  { code: "424", name: "MIQUEL MAS FLORIT" },
  { code: "425", name: "TRASMEDITERRANEA CARGO S.A." },
  { code: "426", name: "HUNSTMAN HOLLAND BU" },
  { code: "429", name: "TRAGINERS DE LLEVANT,S.L." },
  { code: "430", name: "SUMIN. I TRANS. NOIMAC S.L." },
  { code: "432", name: "JAUME CERDA GINES S.L." },
  { code: "433", name: "MAT. DE CONSTRUCCIO CAN MATEU S.L." },
  { code: "435", name: "INVERSIONES AUXELLA S.L." },
  { code: "436", name: "ALMACENES FERRAGUT S.L." },
  { code: "437", name: "OBRES CA'N JUST S.L." },
  { code: "442", name: "TRANSPORTS PEDRO AMENGUAL S.L." },
  { code: "443", name: "VIBRADOS PORRERAS S.A." },
  { code: "444", name: "TRUYOLS NICOLAU S.L." },
  { code: "445", name: "CIA TWENTY MORE S.L." },
  { code: "446", name: "EXCAVACIONES FRANCISCO MUÑOZ S.A." },
  { code: "447", name: "JUAN FERRA BIBILONI" },
  { code: "448", name: "O.P. MAN S.A.- V.O. PUB. S.A. UTE" },
  { code: "450", name: "TTES JAUME CLADERA S.L." },
  { code: "451", name: "PREFABRICADOS SON BASCA S.L." },
  { code: "452", name: "PAVIMENTOS Y OBRAS CARBONELL S.A." },
  { code: "453", name: "AGRIME SAT" },
  { code: "454", name: "BLAU-Q FONAMENTS S.L." },
  { code: "455", name: "CALIZAS CAPELLA S.L." },
  { code: "458", name: "GRUAS SIMONET S.L." },
  { code: "459", name: "ES PLA ES MAGATZEM DE LA VILA S.L." },
  { code: "460", name: "OBRAS GENERALES DRIMALT S.L." },
  { code: "461", name: "EXCAVACIONES MOLL S.L." },
  { code: "462", name: "MAT. I TTES ESPORLES S.L." },
  { code: "463", name: "JAUME FLORIT COMPANY" },
  { code: "464", name: "GABRIEL MAIMO GOMILA" },
  { code: "467", name: "NAVIERA FOS S.L." },
  { code: "469", name: "PERFORACIONES PRINCIPE S.L." },
  { code: "470", name: "SA SITJA DES CIMENT S.L." },
  { code: "471", name: "CONTR.MALLORQ.ASOCIADOS,S.A." },
  { code: "472", name: "KLOOT BALEAR S.L." },
  { code: "473", name: "RESTAURACIONES MALLORCA S.L." },
  { code: "474", name: "CONSTRUCCIONS VILLALONGA LLOPIS S.L." },
  { code: "475", name: "M.C. JAUME SASTRE SOLER S.L." },
  { code: "478", name: "SA VIA DE PORRERES S.L." },
  { code: "479", name: "PROMOFUTUR INSULAR S.L." },
  { code: "480", name: "OBRAS Y REPARACIONES ES CREUERS S.L." },
  { code: "481", name: "CONS. EXC. Y PAVIMEN. HINOJOSA S.L." },
  { code: "482", name: "EXCAVACIONES Y DERRIBOS MOLINA S.L." },
  { code: "483", name: "CAMP DE VARITX S.L." },
  { code: "484", name: "MARIN LLADO CONSTRUCCIONS SL" },
  { code: "485", name: "PEDRO SUREDA BARCELO" },
  { code: "487", name: "OBRES I EXCAVACIONS DOS MAS S.L." },
  { code: "488", name: "CONST. GERMANS BAUÇA JAUME SL" },
  { code: "489", name: "ELDER SERVICIOS Y CONSULTORIA S.L." },
  { code: "500", name: "UTE AZVI-MAN" },
  { code: "501", name: "NETS ESTEMBORERETS S.L." },
  { code: "502", name: "MARTORELL Y BARCELO, C.B." },
  { code: "503", name: "UTE CP SENCELLES" },
  { code: "505", name: "C.I.P. VERGER S.L." },
  { code: "506", name: "ALMACENES LOGAL S.L." },
  { code: "507", name: "PREFABRICATS ARTA C.B." },
  { code: "508", name: "NATURLLARS ECOMATERIALS S.L." },
  { code: "509", name: "AGRICOLA SON SION S.L." },
  { code: "510", name: "CONCRET SINEU CONSTRUCCIONS S.L." },
  { code: "511", name: "TOBAR TRANS DOS MIL S.L." },
  { code: "512", name: "TENEDORA ILLES BLEDES S.L." },
  { code: "513", name: "SERVEIS I COMPLEMENTS ES RAIGUER S.L." },
  { code: "514", name: "NYANY INVERSIONES, S.L." },
  { code: "515", name: "DIEGO BAEZ FERNANDEZ" },
  { code: "516", name: "VIAS Y CONSTRUCCIONES, S.A." },
  { code: "517", name: "MARMOLES GELABERT DIAZ, S.L." },
  { code: "518", name: "PREFABRIC. CARBONELL, S.L." },
  { code: "519", name: "BIEL BAUÇÀ BAUÇÀ" },
  { code: "520", name: "CONST. NOVA 3000, S.L." },
  { code: "521", name: "EXCAVACIONES CETO S.L." },
  { code: "522", name: "JOSE ESTEVA ROIG" },
  { code: "523", name: "GUILLERMO REUS MORA" },
  { code: "524", name: "CONST. GRAN VIOBRA S.L." },
  { code: "525", name: "TTES. BIEL SERVERA S.L." },
  { code: "526", name: "REPLA BALEAR S.L." },
  { code: "527", name: "CONST.I REFOR. JOAN TONI I TONI, C.B." },
  { code: "528", name: "CONST. BARCELO I OBRADOR, S.L." },
  { code: "529", name: "ANTONIO RIOS POL" },
  { code: "530", name: "CONST. PEP MORAGUES S.L." },
  { code: "531", name: "UTE E VARIANTE PTO POLLENÇA" },
  { code: "532", name: "EXCAVACIONS S'HORTA S.A." },
  { code: "533", name: "SON GENER VELL S.L." },
  { code: "534", name: "TONI VENY BARCELO" },
  { code: "535", name: "MARMOLERIA BAUTISTA S.A." },
  { code: "536", name: "MON BLANC S.L." },
  { code: "537", name: "MAT. CONST. OLIVER MORELL, S.L." },
  { code: "538", name: "GUIX I DECORACIO GOMILA GOST S.L." },
  { code: "539", name: "EXC. ADROVER BENNASAR I FILLS S.L." },
  { code: "540", name: "EXCAVACIONES SON CLADERA S.L." },
  { code: "541", name: "PORRERES NOU S.L." },
  { code: "542", name: "NOVASTEIN S.L." },
  { code: "543", name: "MARMOLES FELANITX S.L." },
  { code: "544", name: "CIMENTS LES ILLES S.A." },
  { code: "545", name: "JULIAN DONOSO S.L." },
  { code: "546", name: "MANOBRES ES CABANYAL S.L." },
  { code: "547", name: "BARCELO SEGUI TRANSPORTS S.L." },
  { code: "548", name: "CONST. BARCELO I MAIMO C.B." },
  { code: "549", name: "GUIXOS SOLER VALLESPIR S.L." },
  { code: "550", name: "REFORMES I CONST. DIT I FET S.L." },
  { code: "551", name: "SERVICONS MALLORCA S.L." },
  { code: "552", name: "UTE MAN STA EUGENIA" },
  { code: "553", name: "FORJATS BARMA S.L." },
  { code: "554", name: "GRAVILLERA SON CHIBETLI S.L." },
  { code: "555", name: "MAT. DE CONST. LLUCMAJOR S.L." },
  { code: "556", name: "CONST. RUSTIC DES PLA S.L." },
  { code: "557", name: "CANTERA CAS VILAFRANQUER S.L." },
  { code: "558", name: "MALLORQUINA DE CEMENTOS S.A." },
  { code: "559", name: "TRANSPORTS CAS VILAFRANQUER S.L." },
  { code: "560", name: "SEBASTIA LLINAS MOREY" },
  { code: "561", name: "CRA PALMA-MANACOR CONC. CI MALLORCA S.A." },
  { code: "562", name: "OBRES FERRERICO S.L." },
  { code: "563", name: "COMSA SA Y OBRAS Y PAV MAN SA UTE" },
  { code: "564", name: "UTE VOPSA MAN MA-3040" },
  { code: "565", name: "TTES Y MATERIALES MELLADO E HIJOS S.L." },
  { code: "566", name: "SILVESTRE VICENS BONET" },
  { code: "568", name: "CONSTRUCCIONES PI DEL LLOC S.L." },
  { code: "569", name: "TRANSMAS S.A." },
  { code: "570", name: "EXCAVACIONS JOFRESA CB" },
  { code: "571", name: "CIMIENTOS Y CONSTRUCCIONES SL" },
  { code: "572", name: "CASA SEDRA HIJO S.L." },
  { code: "573", name: "EUROLINEAS MARITIMAS S.A." },
  { code: "574", name: "MANERA MATERIALS I SERVEIS S.L." },
  { code: "575", name: "CARLOS MARCH DELGADO" },
  { code: "576", name: "MASSANELLA 1965 S.A." },
  { code: "577", name: "CONST. SALVADOR PASTOR S.A." },
  { code: "578", name: "AJUNTAMENT DE PORRERES" },
  { code: "579", name: "XISCO MENA" },
  { code: "580", name: "INMOBILIARIA SABRICAP S.L." },
  { code: "581", name: "PEP MOYA REPISO" },
  { code: "582", name: "Casimiro Hdez e Hijos 'LA MARUXIÑA S.A." },
  { code: "583", name: "CAN SOLER S.A." },
  { code: "584", name: "CERAMICA NUESTRA SEÑORA DE LA OLIVA SA" },
  { code: "585", name: "ZURERA YESO BALEAR S.L." },
  { code: "586", name: "RUSSULA 2005 S.L." },
  { code: "587", name: "TRAVAUX ALOKHOWA" },
  { code: "588", name: "CA'S PICAPEDRER S.L." },
  { code: "589", name: "ANTONIO GOST SOCIAS S.L." },
  { code: "590", name: "JAIME LLOMPART CASTAÑER" },
  { code: "591", name: "GUILLEM BAUTISTA VICH" },
  { code: "592", name: "ACCIONA INFRAESTRUCTURAS SA" },
  { code: "593", name: "BUILD THE BEST GESTION SL" },
  { code: "594", name: "TEJAR BANDRIS S.A." },
  { code: "595", name: "SFT INTERNATIONAL ESPAÑA SL" },
  { code: "596", name: "FERROVIAL A. Y GRUPO RODIO KRONSA UTE" },
  { code: "597", name: "SANAU JARDINS SL" },
  { code: "598", name: "EIX 114 SL" },
  { code: "599", name: "TURISMO Y OCIO CAPDEPERA SL" },
  { code: "600", name: "CONS STA MARGALIDA 2009, SL" },
  { code: "601", name: "LLADO MAT DE CONSTRUCCION SA" },
  { code: "602", name: "FAMILIA PALERM S.L." },
  { code: "603", name: "F. BUFI S.L." },
  { code: "604", name: "GELABERT FONTIRROIG SL" },
  { code: "605", name: "S'ESPINAGAR SL" },
  { code: "606", name: "UTE CAN SOLIVELLES" },
  { code: "607", name: "CASTELL CAÑELLAS S.L." },
  { code: "608", name: "HORMORT BALEARES S.A." },
  { code: "609", name: "MIQUEL SERRA RIUTORT" },
  { code: "610", name: "JUAN LLOMPART MOYA" },
  { code: "611", name: "MARMORIS S.L." },
  { code: "612", name: "AJUNTAMENT DE VILAFRANCA DE BONANY" },
  { code: "613", name: "PARROS OBRAS SL" },
  { code: "614", name: "HORMIGONES MANACOR SA" },
  { code: "615", name: "ANDREU SANSO S.L." },
  { code: "616", name: "CAN SABONE S.L." },
  { code: "617", name: "GERMANS NICOLAU CONST. 1970 S.L." },
  { code: "618", name: "PREFABRICATS MAIMO S.L." },
  { code: "619", name: "SANICALOR DE MALLORCA S.L." },
  { code: "620", name: "MATERIALS GAMUNDI SL" },
  { code: "621", name: "UTE VOPSA PYOCSA P SUP CTR LLOSETA" },
  { code: "622", name: "LADRILLERIAS MALLORQUINAS SA" },
  { code: "623", name: "UTE AMER- TERRATEST" },
  { code: "624", name: "PLANTISERV S.L." },
  { code: "625", name: "CONST. LLABRES FELIU S.L.U." },
  { code: "626", name: "CONTENIDORS MANACOR S.L." },
  { code: "627", name: "MATERIALS BALMIR S.L." },
  { code: "628", name: "LAFARGE ARIDOS Y HORMIGONES SAU" },
  { code: "629", name: "FOMENTS DE PROMOCIONS ALARO SL" },
  { code: "630", name: "JUAN FRANCISCO GALLARDO RUIZ" },
  { code: "631", name: "FERNANDO RAMÍREZ SALMERON" },
  { code: "632", name: "DAMIA NICOLAU BARCELO" },
  { code: "633", name: "UTE DRACOTEC" },
  { code: "634", name: "MAN; SIEMENS; VIAL OBRA UTE" },
  { code: "635", name: "CONST. ESTELRICH RIGO S.L." },
  { code: "636", name: "MATIAS VERGER FIOL" },
  { code: "637", name: "KERAKOLL IBERICA S.A." },
  { code: "638", name: "MAVIC CERAMIC S.L." },
  { code: "639", name: "HERO EDIFICACIO PREFABRICADA S.L." },
  { code: "640", name: "CONTENEDORES BARCELO S.L." },
  { code: "641", name: "AJUNTAMENT D'INCA" },
  { code: "642", name: "IMPER. GENERALES VALENCIANAS S.A." },
  { code: "643", name: "MAN SAU- INGEMAXTER SAU UTE" },
  { code: "644", name: "INGESOIL S.L." },
  { code: "645", name: "EFESO SERVICIOS INTEGRALES S.L.U." },
  { code: "646", name: "PUJOL MUNTANER S.L." },
  { code: "647", name: "RIOS POL TRINITY S.L." },
  { code: "648", name: "CONSTRUCCIONS RIUTORT CASTILLA C.B." },
  { code: "649", name: "CAN LLARGARUT S.L." },
  { code: "650", name: "BALTYC OBRAS Y SERVICIOS S.A." },
  { code: "651", name: "ORNICAR S.L." },
  { code: "652", name: "J. BAUZA GENOVART S.L." },
  { code: "653", name: "FIBROTEC S.L." },
  { code: "654", name: "FIMARFUTUR S.L." },
  { code: "655", name: "JAUME PAYERAS VALLESPIR" },
  { code: "656", name: "SON MORAGUES 1921 SLU" },
  { code: "657", name: "JOAN COLL POU" },
  { code: "658", name: "EXPLOTACIONS PEDRA SECA S.L." },
  { code: "659", name: "ALBERT NADAL CRESPI" },
  { code: "660", name: "VIBRATS MORA I ROSSELLO S.L." },
  { code: "661", name: "TM ALCUDIA RECICLATGES S.L." },
  { code: "662", name: "JOAN LLODRA RIERA" },
  { code: "663", name: "RAUL GARCIA ANGELES RICO" },
  { code: "664", name: "CONFORT BALEAR S.A." },
  { code: "665", name: "MARMOLES SINEU S.L." },
  { code: "666", name: "CA'N COMPANY C.B." },
  { code: "667", name: "MARMOLES MOYA E HIJOS S.L." },
  { code: "668", name: "EURO DEPOT ESPAÑA SAU" },
  { code: "669", name: "CIA. TRASMEDITERRANEA S.A." },
  { code: "670", name: "CAN COMPANY SINEU S.L.U." },
  { code: "671", name: "TEJAS BORJA S.A.U." },
  { code: "672", name: "HERO TECNO CONSTRUCCIO S.L." },
  { code: "673", name: "CONSTRUCCIONES Y RESTAURACIONES J.M S.L." },
  { code: "674", name: "BARTOMEU ADROVER MESTRE" },
  { code: "675", name: "CANTERA SA TORRE S.L." },
  { code: "676", name: "MAGATZEM - FERRETERIA CAN PICAFORT S.L." },
  { code: "677", name: "MAGATZEM- FERRETERIA POLLENÇA S.L." },
  { code: "678", name: "JULIA SANSO BAUZA" },
  { code: "679", name: "TRANSINSULAR S.L." },
  { code: "680", name: "HERMANOS MOREY ALZAMORA C.B." },
  { code: "681", name: "TONI VANRELL" },
  { code: "682", name: "SEBASTIAN CALDENTEY S.A." },
  { code: "683", name: "UTE VOPSA PYOCSA DOT SERVICIOS U2 CAMPOS" },
  { code: "684", name: "GABRIEL JUAN JAUME" },
  { code: "685", name: "BIOMASSES BALEARS PER ENERGIA S.L." },
  { code: "686", name: "SOCIEDAD IBERICA DE CONST. ELECTRICAS SA" },
  { code: "687", name: "LUIS CELA MUJICO" },
  { code: "688", name: "TRANSPULVE 2009 S.L." },
  { code: "689", name: "PAVIMENTS I REVESTIMENTS PORRERES S.L." },
  { code: "690", name: "MIQUEL CALDENTEY BONET" },
  { code: "691", name: "GARI BARCELO S.L." },
  { code: "692", name: "TRANSARBONA S.L." },
  { code: "693", name: "ANTONIO BAUZA LLINAS" },
  { code: "694", name: "CRESYROM SPORTS S.L." },
  { code: "695", name: "ROIG CLADERA S.L." },
  { code: "696", name: "EDIFICACIONS MARIA DE LA SALUT S.L." },
  { code: "697", name: "ANTONIA MARIA JAUME OLIVER" },
  { code: "698", name: "BALTASAR TORRES GAYA" },
  { code: "699", name: "ES MAGATZEM DE SON CASTELLO S.L." },
  { code: "700", name: "AQUATARIMA S.L." },
  { code: "701", name: "YEGUADA BAUTISTA VICH S.L." },
  { code: "702", name: "MARMOLES EL PUENTE S.L." },
  { code: "703", name: "AJUNTAMENT D'ARTÀ" },
  { code: "704", name: "SULIAR S.A." },
  { code: "705", name: "TECNO SPORT INTERNACIONAL S.A." },
  { code: "706", name: "FINCA ORLANDO S.L." },
  { code: "707", name: "LOPEZ CHACON S.L." },
  { code: "708", name: "CARMEN TERUEL RODRÍGUEZ" },
  { code: "709", name: "JAIME CABRER GARCIA" },
  { code: "710", name: "TEIDE REFRACTORY SOLUTIONS S.L." },
  { code: "711", name: "MAGATZEM ADROVER S.L." },
  { code: "712", name: "COMPAÑIA MAQUINARIA 93 S.A." },
  { code: "713", name: "EXPLOTACIONS BELLAVISTA S.L." },
  { code: "714", name: "CALDENTEY-HERBON C.B." },
  { code: "715", name: "SUMINISTROS GESER S.L." },
  { code: "716", name: "UTE COLECTOR STA MARIA VOPSA-VITRAC" },
  { code: "717", name: "BIOPOLÍMEROS MAYA S.L." },
  { code: "718", name: "CAN PALMER S.L." },
  { code: "719", name: "GUIXOS MALLORQUINS S.L." },
  { code: "720", name: "MARMOLES ESGRAMAR 2 S.L." },
  { code: "721", name: "RAUL GARCIA ANGELES SANCHEZ" },
  { code: "722", name: "OBRES UPACOR S.L." },
  { code: "723", name: "DECORYL S.L." },
  { code: "724", name: "MALLORQUINA DE ELEM. PARA LA CONST.S.L." },
  { code: "725", name: "MOVIMIENTOS Y LOGISTICA OLIVER S.L." },
  { code: "726", name: "OBRES I CONST. TOMEU ROSSELLO S.L." },
  { code: "727", name: "CORTANA DECOR S.L." },
  { code: "728", name: "CEMENTOS LA UNION S.A." },
  { code: "729", name: "ESPLET/SAT 9453" },
  { code: "730", name: "AMADOR BELTRAN BAUZÀ" },
  { code: "731", name: "ITACA BALEAR SL" },
  { code: "732", name: "ANTONIO BOU BAUZA" },
  { code: "733", name: "PREILLES S.L." },
  { code: "734", name: "AMCOVA BALEAR S.L." },
  { code: "735", name: "TUBOSA BALEAR, S.L." },
  { code: "736", name: "MARBRES PALMA S.A" },
  { code: "737", name: "GUILLERMO BARCELO NICOLAU" },
  { code: "738", name: "TECNIMAC MAQUINARIA S.L." },
  { code: "739", name: "ANTONI JAUME COMAS SIQUIER" },
  { code: "740", name: "TEC. DE CONT. PREV. Y GEST. AMBIENTAL SL" },
  { code: "741", name: "CEMENTOS SON CHIBETLI, S.L.N.E." },
  { code: "742", name: "EXCAV. Y MOVIM. DE TIERRA MOTECAL SL" },
  { code: "743", name: "LADRILLERAS IBICENCAS, S.A." },
  { code: "744", name: "MARMOLERIA MALLORCA, S.L." },
  { code: "745", name: "ROIG OBRES SERVEIS I MEDI AMBIENT, SA" },
  { code: "746", name: "MACIA SERRA BARCELO" },
  { code: "747", name: "SA TEULERA MAGATZEM DE CONST. SL" },
  { code: "748", name: "AGRU.GUINOVART OBRAS Y SERV.HISPANIA SA" },
  { code: "749", name: "HERMANOS GOST SIMO SA" },
  { code: "750", name: "MARTI SERRA FERNANDEZ" },
  { code: "751", name: "CANTERA SON DE LA BAU, S.L." },
  { code: "752", name: "TRANSPORTES INSULARES FORTEZA SL" },
  { code: "753", name: "CLUB NAUTICO SERRANOVA" },
  { code: "754", name: "FARESMAR CARGO S.L." },
  { code: "755", name: "APLICACIONS ENERGÈTIQUES DE LA FUSTA S.L" },
  { code: "756", name: "MARES DE PORRERES SL" },
  { code: "757", name: "CONSTR. JORDI SALAS SEGUI, S.L." },
  { code: "758", name: "MARIA CAÑELLAS I FILLES SL" },
  { code: "759", name: "CONSTRUCCIONES TORMO-SIL, S.L." },
  { code: "760", name: "CMG AGUA Y ENERGIA SL" },
  { code: "761", name: "TRANSPORTES MARITIMOS ALCUDIA S.A." },
  { code: "762", name: "AGRO NIU PRODUCTOS Y SERVICIOS S.L." },
  { code: "763", name: "CONSTRUCCIONES JUAN GALEANO SLU" },
  { code: "764", name: "TEULERA MASCARO S.L." },
  { code: "765", name: "24 DE JUNY CONST. I REFORMES SL" },
  { code: "766", name: "MARES Y PICADIS, S.L." },
  { code: "767", name: "PROFUTUR 2002 S.L." },
  { code: "768", name: "CANTERA CAN CASETES, S.L." },
  { code: "769", name: "INVESIA CONST. Y SERVICIOS SLU" },
  { code: "770", name: "SIMONDO MALLORCA SL" },
  { code: "771", name: "NA MARTINA S.L." },
  { code: "772", name: "PERMISA SL" },
  { code: "773", name: "DECORYL APLICACIONES S.L." },
  { code: "774", name: "MATIAS ARROM BIBILONI" },
  { code: "775", name: "PREFABRICADOS ALGAIDA SL" },
  { code: "776", name: "GESPORTIVA GMB SLU" },
  { code: "777", name: "EXCAVACIONS PELDEMEL S.L." },
  { code: "778", name: "PIEDRAS NATURALES MOSQUERUELA S.L." },
  { code: "779", name: "APLINOR XPRAYTECH SYSTEMS S.L." },
  { code: "780", name: "EXCAVACIONS GUIEM SL" },
  { code: "781", name: "BRICOLAJE BRICOMAN SLU" },
  { code: "782", name: "NINICONS 2000, SL" },
  { code: "783", name: "FRANCESC NICOLAU MAT. DE CONST. S.L." },
  { code: "784", name: "JUAN VANRELL BATLE" },
  { code: "785", name: "CERAMICAS BANDRIS S.L.U." },
  { code: "786", name: "SEBASTIA BARCELO SANSO" },
  { code: "787", name: "TRANSPORTS FONS R S.L." },
  { code: "788", name: "ENRIQUE ARJONA GARI" },
  { code: "789", name: "MARIA ISABEL POZO TARIFA" },
  { code: "790", name: "TRANS CHORIC S.L." },
  { code: "791", name: "TRANSPORTS MIGJORN 2005 S.L." },
  { code: "792", name: "PERMETAL S.L." },
  { code: "793", name: "RAMIS SENCELLES S.L." },
  { code: "794", name: "Ste EL kiHEL TRAV" },
  { code: "795", name: "LOGISTICA URBANA MEDIOAMBIENTAL S.A.U." },
  { code: "796", name: "UTE REORDENACION T.M. FELANITX" },
  { code: "797", name: "TRANSPORTES SON CHIBETLÍ S.L." },
  { code: "798", name: "MURHOTEL CONSTRUCCIONES, S.L." },
  { code: "799", name: "MARMOLES FEGONSAMAR S.L." },
  { code: "800", name: "CONSTRUCCIONS FERRIOL FLORIT S.L." },
  { code: "801", name: "LA HISPANO IGUALADINA S.L." },
  { code: "802", name: "JUAN ANTONIO SALAS Y OTRO CB" },
  { code: "803", name: "UTE MURALLA IBIZA" },
  { code: "804", name: "DIBAPLAC ESPAÑA S.L." },
  { code: "805", name: "GESTIONES DECORATIVAS DEL MAR SL" },
  { code: "806", name: "PEDRO ROSSELLÓ LLULL" },
  { code: "807", name: "PEDRO BERGAS GALLARD" },
  { code: "808", name: "FERROS MURO S.L.U." },
  { code: "810", name: "ENVASES MARTEL S.L." },
  { code: "811", name: "SON BUGADELLAS SA" },
  { code: "812", name: "GUILLERMO DURAN S.A." },
  { code: "813", name: "ARIDS CA'N BUM S.L." },
  { code: "814", name: "EXCAVACIONES Y OBRA PUBLICA BOU S.L." },
  { code: "815", name: "SAPOBLAMAT SL" },
  { code: "816", name: "CONSTRUCTORA SAN JOSE SA" },
  { code: "818", name: "CASA DEPOT S.L." },
  { code: "819", name: "GOMILA MATERIALES DE CONSTRUCCIÓN SA" },
  { code: "820", name: "PALLISER ROMERO S.L." },
  { code: "821", name: "APALLISER S.L." },
  { code: "822", name: "CA'N MARI SERRA 2018 S.L." },
  { code: "823", name: "COPISA.CONST. PIRENAICA S.A. Y AGLOM. FE" },
  { code: "824", name: "POLIVAS S.L." },
  { code: "825", name: "TRANEXMA S.L." },
  { code: "826", name: "VIAS Y CONST. SA Y COEXA UTE" },
  { code: "827", name: "FINCA SON FLOR S.L.U." },
  { code: "828", name: "SISPAL S.L." },
  { code: "829", name: "CA'N TOMEU MATERIALS I SERVEIS S.L." },
  { code: "830", name: "INVERSIONS NIU ALARO S.L." },
  { code: "831", name: "CENTRE TECNOLÒGIC DE LA INDÚSTRIA BALEAR" },
  { code: "832", name: "ACSA OBRAS E INFRAESTRUCTURAS SAU" },
  { code: "833", name: "SON TORRAT CONSTRUCCIONS I SERVEIS S.L." },
  { code: "834", name: "T.M.T. S.L." },
  { code: "835", name: "UTE REAL CLUB NAUTICO P. POLLENÇA" },
  { code: "836", name: "SERMAC C.B." },
  { code: "837", name: "AUTOESCOLA RIBAS SL" },
  { code: "838", name: "CONST. I PROMOCIONS GREGAL 2005 S.L." },
  { code: "839", name: "OBRES M. CAPO S.L." },
  { code: "840", name: "SA MOLADORA S.L." },
  { code: "841", name: "ACCES BALEAR S.L." },
  { code: "842", name: "SHIODOME GROUP 2020 S.L.U." },
  { code: "843", name: "MSP BRICO SANTANYI S.L." },
  { code: "844", name: "GRIMALT INNOVACIÓ I TRADICIÓ S.L." },
  { code: "845", name: "ANTONI BENNASSAR" },
  { code: "846", name: "HERMANOS PARROT S.A." },
  { code: "847", name: "BAUEN EMPRESA CONSTRUCTORA SA" },
  { code: "848", name: "REFOART S.L." },
  { code: "849", name: "VITRAC OBRA PUBLICA S.L." },
  { code: "850", name: "PAVIMENTS LLOSETA S.L." },
  { code: "851", name: "VIBELBA S.L.U." },
  { code: "852", name: "SON VIDA GOLF S.L.U." },
  { code: "853", name: "JAUME ADROVER NADAL" },
  { code: "854", name: "PONT & ROSSELLO S.L." },
  { code: "855", name: "CLUB DE GOLF SON SERVERA" },
  { code: "856", name: "RAFAEL FERNANDEZ DIANA" },
  { code: "857", name: "TOMEU BARCELO S.A." },
  { code: "858", name: "COPISA CONSTRUCTORA PIRENAICA S.A." },
  { code: "859", name: "VIDRERÍES GORDIOLA S.L." },
  { code: "860", name: "PASTOR CAN PICAFORT S.L." },
  { code: "861", name: "PREFABRICATS LLEVANT C.B." },
  { code: "862", name: "AVICOLA SON PEROT S.A." },
  { code: "863", name: "MIQUEL SANSO" },
  { code: "864", name: "DCOD INGENIERIA S.L." },
  { code: "865", name: "MELCHOR MASCARIU SAU Y CONST. EMBAT SA U" },
  { code: "866", name: "ANTONI ROIG TIMONER" },
  { code: "867", name: "SERVEIS SOLAS MARTORELL 2018CB" },
  { code: "868", name: "CONSTRUCCIONES ALEA S.L." },
  { code: "869", name: "MONPLAC ILLES BALEARS S.L." },
  { code: "870", name: "EN CAN'T BALEARES S.L." },
  { code: "871", name: "PREFABRICATS MANERA S.L." },
  { code: "872", name: "HOSPITAL DE MANACOR" },
  { code: "873", name: "RAFEL BOVER MACARIO" },
  { code: "874", name: "MATERIALS AND POOLS S.L." },
  { code: "875", name: "TRASMED GLE S.L." },
  { code: "999", name: "CONTADOS" },
  { code: "1010", name: "VENTAS AL CONTADO" },
  { code: "876", name: "AMENGUAL-F S.L." },
  { code: "877", name: "COPCISA S.A." },
  { code: "878", name: "CA'N GALLET S.L." },
  { code: "879", name: "HORMIGONES S'ARANJASSA S.L." },
  { code: "880", name: "CAN NOT S.L." },
  { code: "881", name: "CA'N XOT S.L." },
  { code: "882", name: "CONSTRUCCIONS SENCELLES 2022 S.L." },
  { code: "883", name: "PRODUCTORES DE PICADIS S.A." },
  { code: "884", name: "FORMIROC S.L." },
  { code: "885", name: "CARBONELL EXCLUSIVE PROPERTIES S.L." },
  { code: "886", name: "JUAN MAIMÓ ESTELRICH" },
  { code: "887", name: "GUILLEM VILLALONGA RAMON" },
  { code: "888", name: "ROBERTO VELASCO CAMINO" },
  { code: "889", name: "UTE CLUB NAUTIC CAN PICAFORT" },
  { code: "890", name: "CATALINA MIR MILLAN" },
  { code: "891", name: "GRAVERA CAN ALOU S.L." },
  { code: "892", name: "PROYECTOS Y PAVIMENTACIONES MALLORCA S.L.U." },
  { code: "893", name: "MASSANELLA MALLORCA S.L." },
  { code: "894", name: "EXC. I TTES JOAN BALLESTER S.L." },
  { code: "895", name: "BLAI LLOPIS AULET" },
  { code: "896", name: "GRIMALT MASCARO S.L." },
  { code: "897", name: "ERNESTO JARDINES S.L.U." },
  { code: "898", name: "IBERMORA CEMENTOS S.L." },
  { code: "899", name: "INGENIERIA Y SEGURIDAD MINERA DE BALEARES S.L." },
  { code: "900", name: "AMURA NÀUTIC S.L." },
  { code: "901", name: "BALEAR DE SERVICIOS Y OBRA CIVIL S.L." },
  { code: "902", name: "RIGEL OVER S.L." },
  { code: "903", name: "TRANSMI- FLUSER S.L." },
  { code: "904", name: "COM DE VIVRADOS Y CONST. S.A." },
  { code: "905", name: "SINEU EXCACACIONS I TRANSPORTS S.L." },
  { code: "906", name: "AGUSTÍ ROGER JARA" },
  { code: "907", name: "CONTRUCTORA BALEARES ANDALUCIA S.L." },
  { code: "908", name: "S'HORT DE SA BASSA S.L." },
  { code: "909", name: "SASTREROCA S.L." },
  { code: "910", name: "TRRANSBETON BALEARES 2022" },
  { code: "911", name: "CARLOS MANUEL FONSECA SANTOS" },
  { code: "912", name: "MANUEL CORTES S.L." },
  { code: "913", name: "UTE AMER E HIJOS Y M. MASCARÓ VERTEDERO" },
  { code: "914", name: "ROSAM C.B" },
  { code: "915", name: "ARIDS I MATERIALS CAN RAMIS S.L." },
  { code: "916", name: "FUSTER & FUSTER VIVIENDAS SINGULARES S.L." },
  { code: "100001", name: "DAVID PUJALT EQUINE MANAGEMENT" },
  { code: "100002", name: "GACARI S.L." },
  { code: "100003", name: "COMPOST I MULCH S.L." },
  { code: "100004", name: "SERVEIS GINARD GARCIES" },
  { code: "100005", name: "MORGAN FUTUR S.L.U." },
  { code: "100006", name: "INVERSIONES SINIUM S.L." },
  { code: "100007", name: "PROMOCIONS RUSTIQUES S.L." },
  { code: "100008", name: "CESGARDEN S.L." },
  { code: "100009", name: "MOVIMENTS DE TERRA SINEU S.L." },
  { code: "929", name: "CONSTRUCCIONS I REFORMES VIVES 2011 S.L." },
  { code: "100010", name: "MARMOLES NEGRE FERRER S.L." },
  { code: "100011", name: "VOREI BALEAR S.L." },
  { code: "100012", name: "KNIFE MECANIC S.L." },
  { code: "100013", name: "CONDOMINIO ONCE DE NOVIEMBRE S XXI" },
  { code: "917", name: "TARIGAMAR S.L." },
  { code: "918", name: "MALENGASHI S.L." },
  { code: "919", name: "AF CAN HENARES S.L." },
  { code: "920", name: "CUATRE RODES ILLES" },
  { code: "921", name: "POLLUX PROJECT" },
  { code: "922", name: "TTES I EXCAVACIONES ENRIQUE ARJONA" },
  { code: "923", name: "VITRAC OBRES I SERVEIS" },
  { code: "924", name: "TAMARELL 22 MANACOR S.L." },
  { code: "925", name: "TRABEGA LOGISTICA S.L." },
  { code: "926", name: "GREEN NATUR CESPED DEPORTIVO S.L." },
  { code: "927", name: "INDUSTRIAL ZURTRADS S.L." },
  { code: "928", name: "HORMIGONES FORT" },
  { code: "929", name: "CONST. I REFORMAS VIVES 2011 S.L." },
  { code: "930", name: "PEDRO JUAN CARRERAS MASCARO" },
  { code: "931", name: "ELESGRU S.L." },
  { code: "932", name: "GOLF PARK ENTERTAINMENT MALLORCA" },
  { code: "933", name: "TRANSPORTALIS 5000 S.L." },
  { code: "934", name: "TRAÇ MATERIALS S.L." },
  { code: "935", name: "CIAL I AUTOMOCION RUBIO S.L." },
  { code: "100014", name: "ECOCREAMOS S.L." },
  { code: "100015", name: "BELLVER RIC 2019 S.L." },
  { code: "100016", name: "PEDRO MEDRANO BEJARANO" },
  { code: "100017", name: "LOUISE DESPONT" },
  { code: "100018", name: "LLUIS MARTORELL POMAR" },
  { code: "940", name: "AMENGUAL SC 25 SLU" },
  { code: "941", name: "SON VALLFOGO S.L." }
];
